/**
 * Author: George Kochera
 * Date: 5/10/2021
 * File: boat_class.js
 * Description: Contains all the functions for manipulating, storing and handling Boats
 */

// Boat Object Definition
/*
    { 
      "id": "abc123",                           # Automatically generated by Datastore
      "name": "Sea Witch",                      # The name of the boat, a string
      "type": "Catamaran",                      # The type of the boat, power boat, sailboat, catamaran etc. a string
      "length": 28,                             # The length of the boat
      "public": true,                           # Boolean. true means the boat is public, false means it's private.
      "owner": "auth0|5eb70257",                # The owner of the boat, value of sub property in the JWT
      "self":"https://appspot.com/boats/abc123" # Optional
    }
*/

var http = require('http')
var datastore = require('./database');
var h = require('./helper');
var Load = require('./load_class')

module.exports = class Boat
{
    constructor(data, request=null)
    {   
        if (data instanceof http.IncomingMessage)
        {
            this.id = null
            this.name = data.body.name;
            this.type = data.body.type;
            this.length = parseInt(data.body.length, 10);
            this.isPublic = data.body.public;
            this.owner = data.sub;
            this.self = null;
            this.loads = [],
            this.key = datastore.key('Boat');
            this.requiredAttributes = ['name', 'type', 'length', 'public']
            this.hasAllFields = this._hasAllFields(data);
        }
        else 
        {
            this.id = data[datastore.KEY].id.toString()
            this.name = data.name;
            this.type = data.type;
            this.length = parseInt(data.length, 10);
            this.isPublic = data.isPublic;
            this.owner = data.owner;
            this.self = request.protocol + "://" + request.get("host") + "/boats/" + data[datastore.KEY].id;
            this.loads = data.loads;
            this.key = h.createBoatKey(this.id)
            this.requiredAttributes = ['name', 'type', 'length', 'public']
            this.hasAllFields = true;
            
        }

    }

    /**
     * Determines if the Boat has all fields filled out.
     * 
     * @returns true if all fields are present.
     */
    _hasAllFields(nodeRequest)
    {
        let nodeRequestBodyKeys = Object.keys(nodeRequest.body);
        return this.requiredAttributes.every(key => nodeRequestBodyKeys.includes(key))
    }

    /**
     * Retrieves all the loads for the boat
     */
    async _retrieveLoads(nodeRequest)
    {
        // Get the actual load for each of the stored load keys
        this.loads = await Promise.all(this.loads.map(async (load) => {
            let [loadResult] = await datastore.get(load);
            let loadObject = new Load(loadResult, nodeRequest);

            return loadObject.getLoadWithoutCarrier();
        }));
    }

    /**
     * Updates the fields in a Boat object.
     * @param {req.body} requestBody An express req.body object.
     * @returns true if at least one field is present.
     */
    updateFields(request)
    {
        let keys = Object.keys(request.body);

        if (keys.length < 1)
        {
            return false;
        }

        keys.map(key => {
            if (this.hasOwnProperty(key))
            {
                this[key] = request.body[key];
            }
        })

        // Ensure users can't try to circumvent integer constraint
        this["length"] = parseInt(this["length"], 10);
        
        return true;
    }
    
    /**
     * Updates all fields in a boat object. If all fields are not included in the request body this function will fail.
     * @param {req.body} request 
     * @returns true iff all fields are inlcuded in the request body.
     */
    updateAllFields(request)
    {
        if (!this._hasAllFields(request))
        {
            return false;
        }
        else
        {
            return this.updateFields(request);
        }
    }

    /**
     * Returns a boat object without metadata
     */
    async getBoat(nodeRequest) {
        await this._retrieveLoads(nodeRequest);
        return {
            id: this.id,
            name: this.name,
            type: this.type,
            length: this.length,
            loads: this.loads,
            public: this.isPublic,
            owner: this.owner,
            self: this.self
        }
    }

    /**
     * Returns a boat object without metadata or loads
     */
    getBoatWithoutLoads() {
    return {
        id: this.id,
        name: this.name,
        type: this.type,
        length: this.length,
        public: this.isPublic,
        owner: this.owner,
        self: this.self
    }
}

    async insert()
    {
        // Construct the key and data for the datastore query
        var entity = {
            key: this.key,
            data: {
                name: this.name,
                type: this.type,
                length: this.length,
                loads: this.loads,
                isPublic: this.isPublic,
                owner: this.owner
            }
        }
        // Insert the new boat
        await datastore.insert(entity);
    }

    async update()
    {
        var entity = {
            key: this.key,
            data: {
                name: this.name,
                type: this.type,
                length: this.length,
                loads: this.loads,
                isPublic: this.isPublic,
                owner: this.owner
            }
        }

        await datastore.update(entity)
    }

    async get(nodeRequest)
    {
        // Now get the boat back so we can display it
        let [boatResult] = await datastore.get(this.key);
        this.id = boatResult[datastore.KEY].id.toString();
        this.name = boatResult.name;
        this.type = boatResult.type;
        this.length = boatResult.length;
        this.loads = boatResult.loads;
        this.isPublic = boatResult.isPublic;
        this.owner = boatResult.owner;
        this.self = nodeRequest.protocol + "://" + nodeRequest.get("host") + "/boats/" + boatResult[datastore.KEY].id
    }

    async removeAllLoads()
    {

        // Update the loads to not have a carrier
        await this.loads.forEach(async load => {
            var [current] = await datastore.get(load);

            var newLoad = {
                volume: current.volume,
                carrier: null,
                content: current.content,
                creation_date: current.creation_date       
            }
            let entity = {
                key: load,
                data: newLoad
            }

            await datastore.update(entity);
        })
    }

    async removeLoad(loadKey)
    {
        // Get all the loads from datastore
        this.loads = this.loads.filter(load => load !== loadKey)

        await this.update();


    }
}